#!/usr/bin/env python3
"""Add the Batch 1-4 GUI/Bitcoin i18n keys to every locale block + the type."""
import re, sys

path = 'src/lib/i18n.ts'
src = open(path).read()

# key -> (en, fr, es, zh, hi, fil, pl, uk, sw)
KEYS = {
  'checkoutTitle': ('Pay fees', 'Payer les frais', 'Pagar cuotas', '缴纳费用', 'शुल्क का भुगतान करें', 'Magbayad ng bayarin', 'Opłać opłaty', 'Сплатити внески', 'Lipa ada'),
  'checkoutHint': ('Quote a fee payment on any rail, then confirm.', 'Obtenez un devis sur n’importe quel rail, puis confirmez.', 'Cotiza un pago en cualquier rail y confirma.', '在任意通道获取费用报价，然后确认。', 'किसी भी रेल पर शुल्क उद्धरण लें, फिर पुष्टि करें।', 'Kumuha ng quote sa anumang rail, pagkatapos kumpirmahin.', 'Uzyskaj wycenę na dowolnym torze, a następnie potwierdź.', 'Отримайте котирування на будь-якому рейлі, потім підтвердьте.', 'Pata quote ya malipo kwenye reli yoyote, kisha thibitisha.'),
  'checkoutAmount': ('Amount (CAD)', 'Montant (CAD)', 'Monto (CAD)', '金额（加元）', 'राशि (CAD)', 'Halaga (CAD)', 'Kwota (CAD)', 'Сума (CAD)', 'Kiasi (CAD)'),
  'checkoutRail': ('Payment rail', 'Rail de paiement', 'Rail de pago', '支付通道', 'भुगतान रेल', 'Rail ng pagbabayad', 'Tor płatności', 'Платіжний рейл', 'Reli ya malipo'),
  'checkoutGetQuote': ('Get quote', 'Obtenir un devis', 'Obtener cotización', '获取报价', 'उद्धरण लें', 'Kumuha ng quote', 'Uzyskaj wycenę', 'Отримати котирування', 'Pata quote'),
  'checkoutConfirm': ('Confirm payment', 'Confirmer le paiement', 'Confirmar pago', '确认付款', 'भुगतान की पुष्टि करें', 'Kumpirmahin ang pagbabayad', 'Potwierdź płatność', 'Підтвердити платіж', 'Thibitisha malipo'),
  'checkoutPaid': ('Payment confirmed', 'Paiement confirmé', 'Pago confirmado', '付款已确认', 'भुगतान की पुष्टि हो गई', 'Kinumpirma ang pagbabayad', 'Płatność potwierdzona', 'Платіж підтверджено', 'Malipo yamethibitishwa'),
  'checkoutQuoteHint': ('The quote locks the rate and reference code.', 'Le devis verrouille le taux et le code de référence.', 'La cotización fija la tasa y el código de referencia.', '报价锁定汇率和参考代码。', 'उद्धरण दर और संदर्भ कोड को लॉक करता है।', 'Ina-lock ng quote ang rate at reference code.', 'Wycena blokuje kurs i kod referencyjny.', 'Котирування фіксує курс і код посилання.', 'Quote inafunga kiwango na msimbo wa marejeleo.'),
  'receiptTxid': ('Transaction', 'Transaction', 'Transacción', '交易', 'लेन-देन', 'Transaksyon', 'Transakcja', 'Транзакція', 'Muamala'),
  'receiptSats': ('Sats locked', 'Sats verrouillés', 'Sats fijados', '锁定的聪', 'लॉक किए गए सैट्स', 'Mga sats na naka-lock', 'Zablokowane satsy', 'Заблоковано сатів', 'Sats zimefungwa'),
  'receiptRate': ('Rate locked', 'Taux verrouillé', 'Tasa fijada', '锁定的汇率', 'लॉक की गई दर', 'Na-lock na rate', 'Zablokowany kurs', 'Заблокований курс', 'Kiwango kimefungwa'),
  'receiptStamp': ('Satohash proof', 'Preuve Satohash', 'Prueba Satohash', 'Satohash 证明', 'Satohash प्रमाण', 'Patunay ng Satohash', 'Dowód Satohash', 'Доказ Satohash', 'Uthibitisho wa Satohash'),
  'receiptCopy': ('Copy invoice', 'Copier la facture', 'Copiar factura', '复制发票', 'इनवॉइस कॉपी करें', 'Kopyahin ang invoice', 'Skopiuj fakturę', 'Скопіювати рахунок', 'Nakili ankara'),
  'monthlyCloseTitle': ('Run the month', 'Clôture du mois', 'Cierre mensual', '月度结算', 'माह चलाएँ', 'Isagawa ang buwan', 'Zamknij miesiąc', 'Закрити місяць', 'Funga mwezi'),
  'monthlyCloseHint': ('Billing → late notices → reconcile, one guided close.', 'Facturation → avis de retard → rapprochement.', 'Facturación → avisos de mora → conciliación.', '账单 → 逾期通知 → 对账，一次完成。', 'बिलिंग → विलंब सूचना → समाधान।', 'Billing → mga abiso sa huli → pagkakasundo.', 'Fakturowanie → wezwania → uzgodnienie.', 'Виставлення рахунків → повідомлення → звірка.', 'Billing → notisi za kuchelewa → upatanisho.'),
  'monthlyClosePeriod': ('Period', 'Période', 'Período', '期间', 'अवधि', 'Panahon', 'Okres', 'Період', 'Kipindi'),
  'monthlyCloseRun': ('Run billing cycle', 'Lancer le cycle de facturation', 'Ejecutar ciclo de facturación', '运行计费周期', 'बिलिंग चक्र चलाएँ', 'Patakbuhin ang cycle ng billing', 'Uruchom cykl fakturowania', 'Запустити цикл виставлення рахунків', 'Endesha mzunguko wa billing'),
  'monthlyCloseCharged': ('Total charged', 'Total facturé', 'Total cobrado', '收费总额', 'कुल शुल्क', 'Kabuuang sinisingil', 'Łącznie naliczono', 'Всього нараховано', 'Jumla inayotozwa'),
  'monthlyCloseNotices': ('Late notices', 'Avis de retard', 'Avisos de mora', '逾期通知', 'विलंब सूचनाएँ', 'Mga abiso sa pagkahuli', 'Wezwania do zapłaty', 'Повідомлення про прострочення', 'Notisi za kuchelewa'),
  'monthlyCloseNone': ('No late notices this cycle', 'Aucun avis de retard ce cycle', 'Sin avisos de mora este ciclo', '本期无逾期通知', 'इस चक्र में कोई विलंब सूचना नहीं', 'Walang abiso ng pagkahuli sa cycle na ito', 'Brak wezwań w tym cyklu', 'Немає прострочень цього циклу', 'Hakuna notisi za kuchelewa mzunguko huu'),
  'monthlyCloseDone': ('Cycle posted to the ledger', 'Cycle publié au grand livre', 'Ciclo registrado en el libro mayor', '周期已记入账本', 'चक्र लेजर में दर्ज हुआ', 'Nai-post ang cycle sa ledger', 'Cykl zaksięgowany', 'Цикл опубліковано в реєстрі', 'Mzunguko umewekwa kwenye leja'),
  'bylawCaseTitle': ('Bylaw enforcement case', 'Cas d’application des règlements', 'Caso de aplicación de reglamentos', '附例执行案件', 'उपनियम प्रवर्तन मामला', 'Kaso ng pagpapatupad ng bylaw', 'Sprawa egzekucji regulaminu', 'Справа про порушення статуту', 'Kesi ya utekelezaji wa sheria ndogo'),
  'bylawCaseHint': ('Complaint → notice → review lock → decision.', 'Plainte → avis → verrou d’examen → décision.', 'Queja → aviso → bloqueo de revisión → decisión.', '投诉 → 通知 → 审查锁定 → 决定。', 'शिकायत → सूचना → समीक्षा लॉक → निर्णय।', 'Reklamo → abiso → lock ng pagsusuri → desisyon.', 'Skarga → wezwanie → blokada przeglądu → decyzja.', 'Скарга → повідомлення → блокування → рішення.', 'Malalamiko → notisi → kufuli la uhakiki → uamuzi.'),
  'bylawCaseNew': ('New complaint', 'Nouvelle plainte', 'Nueva queja', '新投诉', 'नई शिकायत', 'Bagong reklamo', 'Nowa skarga', 'Нова скарга', 'Malalamiko mapya'),
  'bylawCaseEvidence': ('Evidence attached', 'Preuves jointes', 'Evidencia adjunta', '已附证据', 'साक्ष्य संलग्न', 'Nakalakip na ebidensya', 'Dowody dołączone', 'Докази додано', 'Ushahidi umeambatanishwa'),
  'bylawCaseSubmit': ('File complaint', 'Déposer la plainte', 'Presentar queja', '提交投诉', 'शिकायत दर्ज करें', 'Maghain ng reklamo', 'Złóż skargę', 'Подати скаргу', 'Wasilisha malalamiko'),
  'bylawCaseNotice': ('Issue notice', 'Émettre l’avis', 'Emitir aviso', '发出通知', 'सूचना जारी करें', 'Maglabas ng abiso', 'Wydaj wezwanie', 'Видати повідомлення', 'Toa notisi'),
  'bylawCaseLock': ('Review window — fine actions locked', 'Fenêtre d’examen — amendes bloquées', 'Ventana de revisión — multas bloqueadas', '审查期 — 罚款已锁定', 'समीक्षा अवधि — जुर्माना लॉक', 'Window ng pagsusuri — naka-lock ang multa', 'Okno przeglądu — kary zablokowane', 'Вікно перегляду — штрафи заблоковано', 'Dirisha la uhakiki — faini zimefungwa'),
  'bylawCaseUnlocked': ('Review window passed — decision allowed', 'Fenêtre passée — décision possible', 'Ventana pasada — decisión permitida', '审查期已过 — 允许决定', 'समीक्षा अवधि समाप्त — निर्णय संभव', 'Lumipas ang window — pinapayagan ang desisyon', 'Okno minęło — decyzja możliwa', 'Вікно минуло — рішення дозволено', 'Dirisha limepita — uamuzi unaruhusiwa'),
  'bylawCaseFine': ('Impose fine', 'Imposer une amende', 'Imponer multa', '处以罚款', 'जुर्माना लगाएँ', 'Magpataw ng multa', 'Nałóż karę', 'Накласти штраф', 'Weka faini'),
  'bylawCaseNoFine': ('No fine', 'Pas d’amende', 'Sin multa', '不罚款', 'कोई जुर्माना नहीं', 'Walang multa', 'Bez kary', 'Без штрафу', 'Hakuna faini'),
  'bylawCaseMinutes': ('Council minutes ref', 'Réf. procès-verbal du conseil', 'Ref. acta del consejo', '理事会纪要编号', 'परिषद कार्यवृत्त संदर्भ', 'Ref ng minuto ng konseho', 'Ref. protokołu rady', 'Посилання на протокол ради', 'Ref ya kumbukumbu ya baraza'),
  'bylawCaseState': ('Case status', 'État du dossier', 'Estado del caso', '案件状态', 'मामले की स्थिति', 'Katayuan ng kaso', 'Status sprawy', 'Статус справи', 'Hali ya kesi'),
  'membersTitle': ('Member workspace', 'Espace membres', 'Espacio de miembros', '成员工作区', 'सदस्य कार्यक्षेत्र', 'Workspace ng mga miyembro', 'Obszar członków', 'Робочий простір членів', 'Nafasi ya wanachama'),
  'membersHint': ('Owners per lot — trace unit → payments → forms.', 'Propriétaires par lot — tracez unité → paiements → formulaires.', 'Propietarios por lote — trace unidad → pagos → formularios.', '每套业主 — 追踪单元 → 付款 → 表格。', 'प्रति लॉट मालिक — इकाई → भुगतान → फॉर्म।', 'Mga may-ari bawat lote — sundan unit → bayad → form.', 'Właściciele na lokal — śledź jednostkę → płatności → formularze.', 'Власники на лот — прослідкуйте одиницю → платежі → форми.', 'Wamiliki kwa kila loti — fuatilia unit → malipo → fomu.'),
  'membersAdd': ('Add member', 'Ajouter un membre', 'Añadir miembro', '添加成员', 'सदस्य जोड़ें', 'Magdagdag ng miyembro', 'Dodaj członka', 'Додати члена', 'Ongeza mwanachama'),
  'membersEmail': ('Email', 'Courriel', 'Correo', '邮箱', 'ईमेल', 'Email', 'E-mail', 'Ел. пошта', 'Barua pepe'),
  'membersRole': ('Role', 'Rôle', 'Rol', '角色', 'भूमिका', 'Tungkulin', 'Rola', 'Роль', 'Jukumu'),
  'membersEmpty': ('No members yet — add the first owner.', 'Aucun membre — ajoutez le premier propriétaire.', 'Sin miembros — añade al primer propietario.', '暂无成员 — 添加第一位业主。', 'अभी कोई सदस्य नहीं — पहला मालिक जोड़ें।', 'Wala pang miyembro — idagdag ang unang may-ari.', 'Brak członków — dodaj pierwszego właściciela.', 'Немає членів — додайте першого власника.', 'Hakuna wanachama bado — ongeza mmiliki wa kwanza.'),
  'deadlinesTitle': ('What’s due', 'Échéances', 'Qué vence', '待办事项', 'क्या बकाया है', 'Ano ang dapat bayaran', 'Co zalega', 'Що на черзі', 'Nini kinachodaiwa'),
  'deadlinesHint': ('Statutory calendar + open quotes for this council.', 'Calendrier légal + devis ouverts de ce conseil.', 'Calendario legal + cotizaciones abiertas.', '法定日历 + 本理事会的开放报价。', 'वैधानिक कैलेंडर + इस परिषद के खुले उद्धरण।', 'Kalendaryo ng batas + mga bukas na quote para sa konsehong ito.', 'Kalendarz ustawowy + otwarte wyceny.', 'Статутний календар + відкриті котирування.', 'Kalenda ya kisheria + quotes wazi za baraza hili.'),
  'deadlinesOverdue': ('Overdue', 'En retard', 'Vencido', '已逾期', 'अतिदेय', 'Huli na', 'Zaległe', 'Прострочено', 'Imechelewa'),
  'deadlinesDays': ('days', 'jours', 'días', '天', 'दिन', 'araw', 'dni', 'днів', 'siku'),
  'deadlinesEmpty': ('Nothing due right now.', 'Rien à échéance pour l’instant.', 'Nada vence ahora mismo.', '当前没有到期事项。', 'अभी कुछ बकाया नहीं।', 'Wala pang dapat bayaran ngayon.', 'Nic nie zalega.', 'Нічого на черзі.', 'Hakuna kinachodaiwa sasa.'),
  'railsTitle': ('Sovereign rails', 'Rails souverains', 'Rails soberanos', '自主通道', 'सॉवरेन रेल्स', 'Mga sovereign rail', 'Suwerenne tory', 'Суверенні рейли', 'Reli huru'),
  'railsHint': ('Enabled rails, node status, and the live CAD/BTC rate.', 'Rails activés, état des nœuds, taux CAD/BTC en direct.', 'Rails activos, estado de nodos y tasa CAD/BTC en vivo.', '已启用通道、节点状态和实时加元/比特币汇率。', 'सक्षम रेल्स, नोड स्थिति, लाइव CAD/BTC दर।', 'Mga aktibong rail, estado ng node, live na CAD/BTC.', 'Aktywne tory, status węzłów, kurs CAD/BTC.', 'Увімкнені рейли, стан вузлів, курс CAD/BTC.', 'Reli zilizowezeshwa, hali ya node, kiwango cha moja kwa moja cha CAD/BTC.'),
  'railsAsOf': ('as of', 'en date du', 'a partir de', '截至', 'अनुसार', 'mula noong', 'na dzień', 'станом на', 'kufikia'),
  'railsNode': ('Node', 'Nœud', 'Nodo', '节点', 'नोड', 'Node', 'Węzeł', 'Вузол', 'Node'),
  'railsNotConnected': ('Host pending — rails configured, not connected.', 'Hôte en attente — rails configurés, non connectés.', 'Host pendiente — rails configurados, no conectados.', '主机待定 — 通道已配置，未连接。', 'होस्ट लंबित — रेल्स कॉन्फ़िगर, जुड़ी नहीं।', 'Nakabinbin ang host — naka-configure ang rails, hindi pa konektado.', 'Host w przygotowaniu — tory skonfigurowane, niepodłączone.', 'Хост очікує — рейли налаштовані, не підключені.', 'Host inasubiri — reli zimesanidiwa, hazijaunganishwa.'),
  'signingTitle': ('Multisig signing room', 'Salle de signature multisig', 'Sala de firma multisig', '多签签名室', 'मल्टीसिग हस्ताक्षर कक्ष', 'Silid ng pagpirma ng multisig', 'Pokój podpisywania multisig', 'Кімната підписання multisig', 'Chumba cha kusaini multisig'),
  'signingHint': ('Pending PSBTs, signature progress, broadcast when ready.', 'PSBT en attente, progression des signatures.', 'PSBT pendientes, progreso de firmas.', '待处理 PSBT、签名进度、就绪后广播。', 'लंबित PSBT, हस्ताक्षर प्रगति, तैयार होने पर प्रसारण।', 'Mga nakabinbing PSBT, progreso ng pirma, i-broadcast kapag handa.', 'Oczekujące PSBT, postęp podpisów, transmisja gdy gotowe.', 'Очікувані PSBT, прогрес підписів, трансляція.', 'PSBT zinazosubiri, maendeleo ya sahihi, tangaza zikishatayarishwa.'),
  'signingRequired': ('required', 'requis', 'requeridas', '需要', 'आवश्यक', 'kailangan', 'wymagane', 'потрібно', 'inahitajika'),
  'signingBroadcast': ('Broadcast', 'Diffuser', 'Transmitir', '广播', 'प्रसारण', 'I-broadcast', 'Transmisja', 'Трансляція', 'Tangaza'),
  'signingEmpty': ('No pending transactions.', 'Aucune transaction en attente.', 'Sin transacciones pendientes.', '无待处理交易。', 'कोई लंबित लेन-देन नहीं।', 'Walang nakabinbing transaksyon.', 'Brak oczekujących transakcji.', 'Немає очікуваних транзакцій.', 'Hakuna miamala inayosubiri.'),
  'signingReady': ('Ready to broadcast', 'Prêt à diffuser', 'Listo para transmitir', '可以广播', 'प्रसारण के लिए तैयार', 'Handa nang i-broadcast', 'Gotowy do transmisji', 'Готово до трансляції', 'Tayari kutangaza'),
  'signingScan': ('Scan with hardware wallet', 'Scanner avec le portefeuille matériel', 'Escanear con cartera de hardware', '用硬件钱包扫描', 'हार्डवेयर वॉलेट से स्कैन करें', 'I-scan gamit ang hardware wallet', 'Zeskanuj portfelem sprzętowym', 'Сканувати апаратним гаманцем', 'Changanua kwa pochi ya vifaa'),
  'walletTitle': ('Wallet & addresses', 'Portefeuille et adresses', 'Cartera y direcciones', '钱包和地址', 'वॉलेट और पते', 'Wallet at mga address', 'Portfel i adresy', 'Гаманець та адреси', 'Pochi na anwani'),
  'walletHint': ('Registered xpub + per-unit receive addresses.', 'Xpub enregistré + adresses par unité.', 'Xpub registrado + direcciones por unidad.', '已注册 xpub + 每套收款地址。', 'पंजीकृत xpub + प्रति-इकाई प्राप्ति पते।', 'Nakarehistrong xpub + mga address ng pagtanggap bawat unit.', 'Zarejestrowany xpub + adresy odbioru.', 'Зареєстрований xpub + адреси прийому.', 'Xpub iliyosajiliwa + anwani za kupokea kwa kila unit.'),
  'walletAddresses': ('Receive addresses', 'Adresses de réception', 'Direcciones de recepción', '收款地址', 'प्राप्ति पते', 'Mga address ng pagtanggap', 'Adresy odbioru', 'Адреси отримання', 'Anwani za kupokea'),
  'walletCopy': ('Copy', 'Copier', 'Copiar', '复制', 'कॉपी करें', 'Kopyahin', 'Kopiuj', 'Копіювати', 'Nakili'),
  'walletCopied': ('Copied', 'Copié', 'Copiado', '已复制', 'कॉपी हुआ', 'Nakopya', 'Skopiowano', 'Скопійовано', 'Imenakiliwa'),
  'walletExplorer': ('View on mempool.space', 'Voir sur mempool.space', 'Ver en mempool.space', '在 mempool.space 查看', 'mempool.space पर देखें', 'Tingnan sa mempool.space', 'Zobacz na mempool.space', 'Переглянути на mempool.space', 'Tazama kwenye mempool.space'),
  'walletNone': ('Register an xpub to derive receive addresses.', 'Enregistrez un xpub pour dériver les adresses.', 'Registra un xpub para derivar direcciones.', '注册 xpub 以派生收款地址。', 'प्राप्ति पते निकालने के लिए xpub पंजीकृत करें।', 'Magrehistro ng xpub para makakuha ng mga address.', 'Zarejestruj xpub, aby wyprowadzić adresy.', 'Зареєструйте xpub для отримання адрес.', 'Sajili xpub kupata anwani.'),
  'ledgerTitle': ('Ledger explorer', 'Explorateur du grand livre', 'Explorador del libro mayor', '账本浏览器', 'लेजर एक्सप्लोरर', 'Explorer ng ledger', 'Przeglądarka rejestru', 'Оглядач реєстру', 'Kichunguzi cha leja'),
  'ledgerHint': ('Browse the verified hash chain per fund.', 'Parcourez la chaîne de hachage vérifiée par fonds.', 'Explora la cadena de hash verificada por fondo.', '按基金浏览已验证的哈希链。', 'प्रति फंड सत्यापित हैश चेन ब्राउज़ करें।', 'I-browse ang na-verify na hash chain bawat fund.', 'Przeglądaj zweryfikowany łańcuch skrótów.', 'Перегляньте перевірений ланцюг хешів.', 'Vinjari mnyororo wa hashi uliothibitishwa kwa kila mfuko.'),
  'ledgerVerify': ('Verify chain', 'Vérifier la chaîne', 'Verificar cadena', '验证链', 'चेन सत्यापित करें', 'I-verify ang chain', 'Zweryfikuj łańcuch', 'Перевірити ланцюг', 'Thibitisha mnyororo'),
  'ledgerVerified': ('Chain verified ✓', 'Chaîne vérifiée ✓', 'Cadena verificada ✓', '链已验证 ✓', 'चेन सत्यापित ✓', 'Na-verify ang chain ✓', 'Łańcuch zweryfikowany ✓', 'Ланцюг перевірено ✓', 'Mnyororo umethibitishwa ✓'),
  'ledgerCsv': ('Export CSV', 'Exporter CSV', 'Exportar CSV', '导出 CSV', 'CSV निर्यात करें', 'I-export ang CSV', 'Eksportuj CSV', 'Експорт CSV', 'Hamisha CSV'),
  'ledgerEmpty': ('No entries in this fund yet.', 'Aucune entrée dans ce fonds.', 'Sin entradas en este fondo.', '该基金暂无记录。', 'इस फंड में अभी कोई प्रविष्टि नहीं।', 'Wala pang entry sa fund na ito.', 'Brak wpisów w tym funduszu.', 'Немає записів у цьому фонді.', 'Hakuna maingizo katika mfuko huu bado.'),
  'exportTitle': ('Export center', 'Centre d’export', 'Centro de exportación', '导出中心', 'निर्यात केंद्र', 'Export center', 'Centrum eksportu', 'Центр експорту', 'Kituo cha uhamishaji'),
  'exportHint': ('Portable JSON, CRT bundle, certificates, ledger CSV.', 'JSON portable, lot CRT, certificats, CSV du grand livre.', 'JSON portátil, paquete CRT, certificados, CSV.', '可移植 JSON、CRT 包、证书、账本 CSV。', 'पोर्टेबल JSON, CRT बंडल, प्रमाणपत्र, लेजर CSV।', 'Portable JSON, CRT bundle, certificates, ledger CSV.', 'Przenośny JSON, pakiet CRT, certyfikaty, CSV rejestru.', 'Портативний JSON, пакет CRT, сертифікати, CSV реєстру.', 'JSON inayobebeka, kifurushi cha CRT, hati, CSV ya leja.'),
  'managerTitle': ('Members & roles', 'Membres et rôles', 'Miembros y roles', '成员和角色', 'सदस्य और भूमिकाएँ', 'Mga miyembro at tungkulin', 'Członkowie i role', 'Члени та ролі', 'Wanachama na majukumu'),
  'managerHint': ('Invite accounts, assign roles, hand off temp passwords.', 'Invitez, attribuez des rôles, remettez les mots de passe.', 'Invita, asigna roles, entrega contraseñas temporales.', '邀请账户、分配角色、移交临时密码。', 'खाते आमंत्रित करें, भूमिकाएँ दें, अस्थायी पासवर्ड दें।', 'Mag-imbita, magtalaga ng tungkulin, ibigay ang temp password.', 'Zaproś, przydziel role, przekaż hasła tymczasowe.', 'Запрошуйте, призначайте ролі, передавайте тимчасові паролі.', 'Alika, gawa majukumu, kaba nywila za muda.'),
  'managerInvite': ('Invite', 'Inviter', 'Invitar', '邀请', 'आमंत्रित करें', 'Mag-imbita', 'Zaproś', 'Запросити', 'Alika'),
  'managerTempPassword': ('Temporary password', 'Mot de passe temporaire', 'Contraseña temporal', '临时密码', 'अस्थायी पासवर्ड', 'Pansamantalang password', 'Hasło tymczasowe', 'Тимчасовий пароль', 'Nywila ya muda'),
  'managerEmpty': ('Only you so far — invite your council.', 'Vous seul pour l’instant — invitez votre conseil.', 'Solo tú por ahora — invita a tu consejo.', '目前只有你 — 邀请你的理事会。', 'अभी केवल आप — अपनी परिषद को आमंत्रित करें।', 'Ikaw lang sa ngayon — imbitahin ang iyong konseho.', 'Na razie tylko Ty — zaproś swoją radę.', 'Поки лише ви — запросіть свою раду.', 'Ni wewe pekee kwa sasa — alika baraza lako.'),
  'rateTitle': ('Live CAD/BTC', 'CAD/BTC en direct', 'CAD/BTC en vivo', '实时加元/比特币', 'लाइव CAD/BTC', 'Live na CAD/BTC', 'CAD/BTC na żywo', 'CAD/BTC наживо', 'CAD/BTC moja kwa moja'),
  'rateUpdated': ('updated', 'mis à jour', 'actualizado', '已更新', 'अपडेट हुआ', 'na-update', 'zaktualizowano', 'оновлено', 'imesasishwa'),
  'eduCrf': ('What is the CRF?', 'Qu’est-ce que le CRF ?', '¿Qué es el CRF?', '什么是 CRF？', 'CRF क्या है?', 'Ano ang CRF?', 'Czym jest CRF?', 'Що таке CRF?', 'CRF ni nini?'),
  'eduCrfText': ('The Contingency Reserve Fund — at least 10% of annual contributions, held separately for major repairs.', 'Le fonds de réserve — au moins 10 % des cotisations annuelles, séparé pour les grosses réparations.', 'El fondo de reserva — al menos 10 % de las contribuciones anuales, separado.', '应急储备金 — 每年至少 10% 的供款，专用于重大维修。', 'आकस्मिक आरक्षित कोष — वार्षिक योगदान का कम से कम 10%, प्रमुख मरम्मत के लिए।', 'Ang Contingency Reserve Fund — hindi bababa sa 10% ng taunang kontribusyon.', 'Fundusz rezerwowy — co najmniej 10% rocznych składek.', 'Резервний фонд — щонайменше 10% річних внесків.', 'Mfuko wa Akiba — angalau 10% ya michango ya kila mwaka.'),
  'eduMultisig': ('What is multisig?', 'Qu’est-ce que le multisig ?', '¿Qué es multisig?', '什么是多重签名？', 'मल्टीसिग क्या है?', 'Ano ang multisig?', 'Czym jest multisig?', 'Що таке multisig?', 'Multisig ni nini?'),
  'eduMultisigText': ('A wallet that needs multiple signatures to spend — e.g. 3 of 5 council members.', 'Un portefeuille nécessitant plusieurs signatures — ex. 3 sur 5 membres.', 'Una cartera que requiere varias firmas — p. ej. 3 de 5.', '需要多重签名才能使用的钱包 — 例如 5 人中 3 人。', 'एक वॉलेट जिसे खर्च करने के लिए कई हस्ताक्षर चाहिए — जैसे 5 में से 3।', 'Isang wallet na nangangailangan ng maraming pirma — hal. 3 sa 5.', 'Portfel wymagający wielu podpisów — np. 3 z 5.', 'Гаманець, що потребує кількох підписів — напр., 3 з 5.', 'Pochi inayohitaji sahihi nyingi — mf. 3 kati ya 5.'),
  'eduLnurl': ('What is LNURL?', 'Qu’est-ce que LNURL ?', '¿Qué es LNURL?', '什么是 LNURL？', 'LNURL क्या है?', 'Ano ang LNURL?', 'Czym jest LNURL?', 'Що таке LNURL?', 'LNURL ni nini?'),
  'eduLnurlText': ('A Lightning payment standard — scan a QR, the rate locks for 15 minutes.', 'Un standard de paiement Lightning — scannez un QR, taux verrouillé 15 min.', 'Un estándar Lightning — escanea un QR, tasa fijada 15 min.', '一种闪电支付标准 — 扫描二维码，汇率锁定 15 分钟。', 'एक लाइटनिंग भुगतान मानक — QR स्कैन करें, दर 15 मिनट लॉक।', 'Isang Lightning standard — i-scan ang QR, naka-lock ang rate ng 15 min.', 'Standard Lightning — skanuj QR, kurs blokowany na 15 min.', 'Стандарт Lightning — скануйте QR, курс фіксується на 15 хв.', 'Kiwango cha Lightning — changanua QR, kiwango hufungwa kwa dakika 15.'),
  'eduOts': ('What is OTS?', 'Qu’est-ce que l’OTS ?', '¿Qué es OTS?', '什么是 OTS？', 'OTS क्या है?', 'Ano ang OTS?', 'Czym jest OTS?', 'Що таке OTS?', 'OTS ni nini?'),
  'eduOtsText': ('OpenTimestamps — anchors a hash to Bitcoin so you can prove when a record existed.', 'OpenTimestamps — ancre un hachage sur Bitcoin pour prouver l’existence.', 'OpenTimestamps — ancla un hash a Bitcoin para probar cuándo existió.', 'OpenTimestamps — 将哈希锚定到比特币以证明记录存在的时间。', 'OpenTimestamps — हैश को बिटकॉइन पर एंकर करता है।', 'OpenTimestamps — ina-angkla ang hash sa Bitcoin.', 'OpenTimestamps — zakotwicza skrót na Bitcoin.', 'OpenTimestamps — закріплює хеш у Bitcoin.', 'OpenTimestamps — huweka hashi kwenye Bitcoin.'),
  'eduDca': ('CRF % at risk', 'CRF % en jeu', 'CRF % en riesgo', '风险 CRF 百分比', 'जोखिम में CRF %', 'CRF % na nakataya', 'CRF % zagrożony', 'CRF % під ризиком', 'CRF % hatarini'),
  'eduDcaText': ('The share of the reserve fund the DCA plan would move to the BTC war chest.', 'La part du fonds de réserve que le DCA déplacerait vers le coffre BTC.', 'La parte del fondo que el DCA movería al cofre BTC.', 'DCA 计划将转入 BTC 金库的储备金份额。', 'आरक्षित कोष का हिस्सा जो DCA BTC कोष में भेजेगा।', 'Ang bahagi ng reserba na ililipat ng DCA sa BTC war chest.', 'Część funduszu, którą DCA przeniósłby do skarbca BTC.', 'Частка фонду, яку DCA перемістить у BTC-скарбницю.', 'Sehemu ya mfuko ambayo DCA ingehamisha kwa hazina ya BTC.'),
  'designTitle': ('Design system', 'Système de design', 'Sistema de diseño', '设计系统', 'डिज़ाइन सिस्टम', 'Design system', 'System projektowania', 'Дизайн-система', 'Mfumo wa muundo'),
  'designIntro': ('Tokens, type, and components — the OpenStrata design language.', 'Jetons, typographie et composants — le langage OpenStrata.', 'Tokens, tipografía y componentes — el lenguaje OpenStrata.', '令牌、字体和组件 — OpenStrata 设计语言。', 'टोकन, टाइप और घटक — OpenStrata डिज़ाइन भाषा।', 'Tokens, type, at components — ang wika ng disenyo ng OpenStrata.', 'Tokeny, typografia i komponenty — język OpenStrata.', 'Токени, типографіка та компоненти — мова OpenStrata.', 'Tokeni, fonti na vipengele — lugha ya muundo ya OpenStrata.'),
  'themeBrokerage': ('Brokerage theme', 'Thème courtier', 'Tema de corretaje', '经纪主题', 'ब्रोकरेज थीम', 'Tema ng brokerage', 'Motyw brokerski', 'Брокерська тема', 'Mandhari ya wakala'),
  'themeBrand': ('Brand accent', 'Accent de marque', 'Acento de marca', '品牌强调色', 'ब्रांड एक्सेंट', 'Brand accent', 'Akcent marki', 'Акцент бренду', 'Rangi ya chapa'),

  # ---- Batch 2 (next 20) ----
  'rosaTitle': ('Rosa — compliance assistant', 'Rosa — assistant de conformité', 'Rosa — asistente de cumplimiento', 'Rosa — 合规助手', 'रोसा — अनुपालन सहायक', 'Rosa — katulong sa pagsunod', 'Rosa — asystent zgodności', 'Rosa — асистент із відповідності', 'Rosa — msaidizi wa uzingatiaji'),
  'rosaIntro': ('Ask BC strata law questions; Rosa answers with citations only.', 'Posez vos questions sur le droit des copropriétés en BC ; Rosa ne répond qu’avec des citations.', 'Haz preguntas sobre la ley de estratos de BC; Rosa responde solo con citas.', '提出卑诗省共管法律问题；Rosa 仅引用来源作答。', 'BC स्ट्राटा कानून के प्रश्न पूछें; रोसा केवल उद्धरण के साथ उत्तर देता है।', 'Magtanong tungkol sa batas ng strata sa BC; sumasagot lang ang Rosa nang may siping.', 'Zadawaj pytania o prawo BC; Rosa odpowiada wyłącznie z cytatami.', 'Ставте запитання про право BC; Rosa відповідає лише з цитатами.', 'Uliza maswali ya sheria ya strata ya BC; Rosa hujibu kwa nukuu tu.'),
  'rosaPlaceholder': ('Ask Rosa… e.g. “What are the rules for short-term rentals?”', 'Demandez à Rosa… p. ex. « Quelles sont les règles pour la location à court terme ? »', 'Pregunta a Rosa… p. ej. “¿Cuáles son las reglas para alquileres a corto plazo?”', '向 Rosa 提问… 例如“短租的规定是什么？”', 'रोसा से पूछें… जैसे “अल्पकालिक किराये के नियम क्या हैं?”', 'Magtanong kay Rosa… hal. “Ano ang mga patakaran para sa panandaliang paupahan?”', 'Zapytaj Rosę… np. „Jakie są zasady wynajmu krótkoterminowego?”', 'Запитайте Rosa… напр. «Які правила короткострокової оренди?»', 'Uliza Rosa… mf. “Ni kanuni gani za kukodisha kwa muda mfupi?”'),
  'rosaSend': ('Ask', 'Demander', 'Preguntar', '提问', 'पूछें', 'Magtanong', 'Zapytaj', 'Запитати', 'Uliza'),
  'rosaUncertain': ('Rosa flagged this as date/fact-dependent — verify before acting.', 'Rosa signale que cela dépend de dates/faits — vérifiez avant d’agir.', 'Rosa marcó esto como dependiente de fechas/hechos — verifica antes de actuar.', 'Rosa 标记此回答依赖日期/事实 — 行动前请核实。', 'रोसा ने इसे तिथि/तथ्य-निर्भर बताया — कार्रवाई से पहले सत्यापित करें।', 'Minarkahan ni Rosa ito bilang nakadepende sa petsa/katotohanan — i-verify muna.', 'Rosa oznaczyła to jako zależne od dat/faktów — zweryfikuj przed działaniem.', 'Rosa позначила це як залежне від дат/фактів — перевірте перед діями.', 'Rosa imebainisha hili kuwa linategemea tarehe/ukweli — thibitisha kabla ya kutenda.'),
  'rosaNoMatch': ('No controlling source found — Rosa will not guess. Rephrase or ask a licensed professional.', 'Aucune source déterminante trouvée — Rosa ne devine pas. Reformulez ou consultez un professionnel.', 'No se encontró fuente determinante — Rosa no adivina. Reformula o consulta a un profesional.', '未找到权威来源 — Rosa 不会猜测。请改写问题或咨询专业人士。', 'कोई निर्णायक स्रोत नहीं मिला — रोसा अनुमान नहीं लगाता। पुनः पूछें।', 'Walang nakitang source — hindi huhula si Rosa. Mag-iba ng tanong o kumonsulta sa propesyonal.', 'Nie znaleziono źródła — Rosa nie zgaduje. Przeformułuj lub skonsultuj się.', 'Джерело не знайдено — Rosa не вгадує. Переформулюйте або зверніться до фахівця.', 'Hakuna chanzo kilichopatikana — Rosa hatabuni. Badilisha swali au wasiliana na mtaalamu.'),
  'rosaDemo': ('Demo answers draw on the built-in BC compliance knowledge base. Sign in for the live corpus.', 'Les réponses de démo s’appuient sur la base de connaissances BC intégrée. Connectez-vous pour le corpus en direct.', 'Las respuestas demo usan la base de conocimiento BC integrada. Inicia sesión para el corpus en vivo.', '演示答案基于内置的 BC 合规知识库。登录后可访问实时语料。', 'डेमो उत्तर अंतर्निहित BC अनुपालन ज्ञानकोष से हैं। लाइव कॉर्पस के लिए साइन इन करें।', 'Ang demo answers ay mula sa built-in na BC knowledge base. Mag-sign in para sa live corpus.', 'Odpowiedzi demo korzystają z wbudowanej bazy BC. Zaloguj się, aby uzyskać żywy korpus.', 'Демо-відповіді з вбудованої бази BC. Увійдіть для живого корпусу.', 'Majibu ya demo yanatokana na msingi wa maarifa wa BC. Ingia kwa data halisi.'),
  'demoLabel': ('Demo', 'Démo', 'Demo', '演示', 'डेमो', 'Demo', 'Demo', 'Демо', 'Demo'),
  'wizardRegister': ('Register this building', 'Enregistrer cet immeuble', 'Registrar este edificio', '注册此楼宇', 'इस भवन को पंजीकृत करें', 'Irehistro ang gusaling ito', 'Zarejestruj ten budynek', 'Зареєструвати цю будівлю', 'Sajili jengo hili'),
  'wizardRegistered': ('Building registered to your workspace', 'Immeuble enregistré dans votre espace', 'Edificio registrado en tu espacio', '楼宇已注册到您的工作区', 'भवन आपके कार्यक्षेत्र में पंजीकृत हुआ', 'Nakarehistro ang gusali sa iyong workspace', 'Budynek zarejestrowany w Twoim obszarze', 'Будівлю зареєстровано у вашому просторі', 'Jengo limesajiliwa kwenye nafasi yako'),
  'scanToPay': ('Scan to pay', 'Scanner pour payer', 'Escanea para pagar', '扫码支付', 'भुगतान के लिए स्कैन करें', 'I-scan para magbayad', 'Zeskanuj, aby zapłacić', 'Скануйте, щоб оплатити', 'Changanua kulipa'),
  'openInWallet': ('Open in wallet', 'Ouvrir dans le portefeuille', 'Abrir en cartera', '在钱包中打开', 'वॉलेट में खोलें', 'Buksan sa wallet', 'Otwórz w portfelu', 'Відкрити в гаманці', 'Fungua kwenye pochi'),
  'formsTrackerTitle': ('Forms & 7-day tracker', 'Formulaires et suivi 7 jours', 'Formularios y seguimiento de 7 días', '表格和 7 天跟踪', 'फॉर्म और 7-दिन ट्रैकर', 'Mga form at 7-araw na tracker', 'Formularze i 7-dniowy tracker', 'Форми та 7-денний трекер', 'Fomu na kifuatiliaji cha siku 7'),
  'formsTrackerHint': ('Issue Form B/F certificates with the statutory delivery countdown.', 'Émettez les certificats B/F avec le compte à rebours légal.', 'Emite certificados B/F con la cuenta regresiva legal.', '签发 B/F 证书并跟踪法定交付倒计时。', 'B/F प्रमाणपत्र जारी करें और वैधानिक डिलीवरी काउंटडाउन दिखाएँ।', 'Mag-issue ng Form B/F na may statutory countdown.', 'Wystawiaj certyfikaty B/F z ustawowym odliczaniem.', 'Видавайте сертифікати B/F із статутним відліком.', 'Toa hati za Form B/F na hesabu ya kisheria.'),
  'formsRequestDate': ('Request date', 'Date de demande', 'Fecha de solicitud', '请求日期', 'अनुरोध तिथि', 'Petsa ng kahilingan', 'Data żądania', 'Дата запиту', 'Tarehe ya ombi'),
  'formsDeliverBy': ('Deliver by', 'À livrer avant', 'Entregar antes del', '交付期限', 'डिलीवरी तिथि', 'Ihatid bago ang', 'Dostarczyć do', 'Доставити до', 'Wasilisha ifikapo'),
  'formsDaysLeft': ('days left', 'jours restants', 'días restantes', '剩余天数', 'दिन शेष', 'araw na natitira', 'pozostało dni', 'днів залишилось', 'siku zimesalia'),
  'formsIssueB': ('Issue Form B', 'Émettre le formulaire B', 'Emitir Formulario B', '签发 B 表', 'फॉर्म B जारी करें', 'Mag-issue ng Form B', 'Wystaw Formularz B', 'Видати форму B', 'Toa Form B'),
  'formsIssueF': ('Issue Form F', 'Émettre le formulaire F', 'Emitir Formulario F', '签发 F 表', 'फॉर्म F जारी करें', 'Mag-issue ng Form F', 'Wystaw Formularz F', 'Видати форму F', 'Toa Form F'),
  'myUnitTitle': ('My unit', 'Mon unité', 'Mi unidad', '我的单元', 'मेरी इकाई', 'Ang aking unit', 'Moja jednostka', 'Мій блок', 'Unit yangu'),
  'myUnitHint': ('Your lot, its ledger, and your payments — at a glance.', 'Votre lot, son grand livre et vos paiements — d’un coup d’œil.', 'Tu lote, su libro mayor y tus pagos — de un vistazo.', '您的单元、账本和付款 — 一目了然。', 'आपका लॉट, उसका लेजर और भुगतान — एक नज़र में।', 'Ang iyong lot, ledger, at bayad — sa isang sulyap.', 'Twój lokal, rejestr i płatności — na pierwszy rzut oka.', 'Ваш лот, реєстр і платежі — одним поглядом.', 'Loti yako, leja na malipo — kwa mtazamo mmoja.'),
  'myUnitNoMatch': ('No member record for your account yet.', 'Aucun dossier de membre pour votre compte.', 'Aún no hay registro de miembro para tu cuenta.', '您的账户暂无成员记录。', 'आपके खाते के लिए अभी कोई सदस्य रिकॉर्ड नहीं।', 'Wala pang member record para sa iyong account.', 'Brak rekordu członka dla Twojego konta.', 'Немає запису члена для вашого акаунта.', 'Hakuna rekodi ya mwanachama kwa akaunti yako bado.'),
  'ballotTitle': ('Ballot voting engine', 'Moteur de vote par scrutin', 'Motor de votación por boleta', '投票引擎', 'मतदान इंजन', 'Ballot voting engine', 'Silnik głosowania', 'Двигун голосування', 'Injini ya upigaji kura'),
  'ballotHint': ('Roll-call resolution with per-unit entitlements.', 'Résolution par appel nominal avec droits par unité.', 'Resolución por lista con derechos por unidad.', '按单元表决权的点名决议。', 'प्रति-इकाई अधिकारों के साथ रोल-कॉल प्रस्ताव।', 'Roll-call resolution na mga karapatan bawat unit.', 'Rezolucja imienna z prawami jednostek.', 'Поіменна резолюція з правами одиниць.', 'Azimio la kuwaita kila unit na haki zake.'),
  'ballotResolution': ('Resolution text', 'Texte de la résolution', 'Texto de la resolución', '决议文本', 'प्रस्ताव पाठ', 'Teksto ng resolusyon', 'Tekst rezolucji', 'Текст резолюції', 'Maandishi ya azimio'),
  'ballotCast': ('Cast ballot', 'Voter', 'Emitir voto', '投票', 'मत डालें', 'Maghain ng balota', 'Oddaj głos', 'Проголосувати', 'Piga kura'),
  'ballotTie': ('Tie — the chair casts the deciding vote', 'Égalité — le président vote de manière décisive', 'Empate — el presidente vota de forma decisiva', '平局 — 主席投出决定性一票', 'बराबरी — अध्यक्ष निर्णायक मत देते हैं', 'Tie — ang chair ang magpapasya', 'Remis — przewodniczący decyduje', 'Нічия — голова вирішує', 'Sare — mwenyekiti huamua'),
  'ballotExport': ('Export minutes', 'Exporter le procès-verbal', 'Exportar acta', '导出纪要', 'कार्यवृत्त निर्यात करें', 'I-export ang minuto', 'Eksportuj protokół', 'Експортувати протокол', 'Hamisha kumbukumbu'),
  'noticeTitle': ('Meeting notice', 'Avis de réunion', 'Aviso de reunión', '会议通知', 'बैठक सूचना', 'Abiso ng pulong', 'Zawiadomienie o spotkaniu', 'Повідомлення про збори', 'Notisi ya mkutano'),
  'noticeHint': ('Statutory notice windows — AGM 14 days, council 7 days.', 'Délais légaux — AGM 14 jours, conseil 7 jours.', 'Plazos legales — AGM 14 días, consejo 7 días.', '法定通知期 — 年度大会 14 天，理事会 7 天。', 'वैधानिक अधिसूचना — AGM 14 दिन, परिषद 7 दिन।', 'Statutory windows — AGM 14 araw, council 7 araw.', 'Terminy ustawowe — AGM 14 dni, rada 7 dni.', 'Статутні терміни — AGM 14 днів, рада 7 днів.', 'Madirisha ya kisheria — AGM siku 14, baraza siku 7.'),
  'noticeType': ('Meeting type', 'Type de réunion', 'Tipo de reunión', '会议类型', 'बैठक प्रकार', 'Uri ng pulong', 'Typ spotkania', 'Тип зборів', 'Aina ya mkutano'),
  'noticeWhen': ('Date & time', 'Date et heure', 'Fecha y hora', '日期和时间', 'तिथि और समय', 'Petsa at oras', 'Data i godzina', 'Дата й час', 'Tarehe na saa'),
  'noticeWhere': ('Place', 'Lieu', 'Lugar', '地点', 'स्थान', 'Lugar', 'Miejsce', 'Місце', 'Mahali'),
  'noticePrint': ('Print notice', 'Imprimer l’avis', 'Imprimir aviso', '打印通知', 'सूचना प्रिंट करें', 'I-print ang abiso', 'Drukuj zawiadomienie', 'Роздрукувати повідомлення', 'Chapisha notisi'),
  'caseFileTitle': ('Bylaw case file', 'Dossier du cas', 'Expediente del caso', '附例案件档案', 'मामला फ़ाइल', 'Case file ng bylaw', 'Akta sprawy', 'Файл справи', 'Faili la kesi'),
  'caseFileHint': ('CRT-ready evidence bundle for this case.', 'Dossier de preuves prêt pour la CRT.', 'Paquete de evidencia listo para CRT.', '为本案件生成 CRT 就绪的证据包。', 'इस मामले के लिए CRT-तैयार साक्ष्य बंडल।', 'CRT-ready evidence bundle para sa kasong ito.', 'Pakiet dowodowy gotowy dla CRT.', 'Пакет доказів, готовий для CRT.', 'Kifurushi cha ushahidi tayari kwa CRT.'),
  'caseFilePrint': ('Print case file', 'Imprimer le dossier', 'Imprimir expediente', '打印案件档案', 'मामला फ़ाइल प्रिंट करें', 'I-print ang case file', 'Drukuj akta sprawy', 'Роздрукувати файл справи', 'Chapisha faili la kesi'),
  'minutesTitle': ('Meeting minutes', 'Procès-verbal', 'Acta de la reunión', '会议纪要', 'बैठक कार्यवृत्त', 'Minuto ng pulong', 'Protokół ze spotkania', 'Протокол зборів', 'Kumbukumbu za mkutano'),
  'healthBasedOn': ('Based on deadlines, Form K gaps, and AR', 'Basé sur les échéances, les lacunes du formulaire K et les AR', 'Basado en plazos, brechas del Formulario K y AR', '基于截止日期、K 表缺口和应收账款', 'समय-सीमा, फॉर्म K अंतराल और AR पर आधारित', 'Batay sa mga deadline, gaps ng Form K, at AR', 'Na podstawie terminów, luk formularza K i AR', 'На основі термінів, прогалин форми K та AR', 'Kulingana na muda, mapungufu ya Form K na AR'),
  'balancesTitle': ('On-chain balances', 'Soldes on-chain', 'Saldos en cadena', '链上余额', 'ऑन-चेन शेष', 'Mga balanse sa on-chain', 'Salda on-chain', 'Баланси on-chain', 'Mizani ya on-chain'),
  'balancesHint': ('Per-address sats from the public mempool.space API.', 'Sats par adresse via l’API publique mempool.space.', 'Sats por dirección desde la API pública de mempool.space.', '通过公共 mempool.space API 获取每地址聪。', 'सार्वजनिक mempool.space API से प्रति-पता सैट्स।', 'Sats bawat address mula sa public mempool.space API.', 'Satsy na adres z publicznego API mempool.space.', 'Сати на адресу з публічного API mempool.space.', 'Sats kwa kila anwani kutoka API ya umma ya mempool.space.'),
  'balancesReceived': ('received', 'reçu', 'recibido', '已收', 'प्राप्त', 'natanggap', 'otrzymano', 'отримано', 'imepokelewa'),
  'balancesConfirmed': ('confirmed', 'confirmé', 'confirmado', '已确认', 'पुष्ट', 'nakumpirma', 'potwierdzone', 'підтверджено', 'imethibitishwa'),
  'dcaTitle': ('War chest DCA planner', 'Planificateur DCA du coffre', 'Planificador DCA del cofre', '金库 DCA 规划器', 'युद्ध कोष DCA योजनाकार', 'DCA planner ng war chest', 'Planer DCA skarbca', 'Планувальник DCA скарбниці', 'Kipangaji cha DCA cha hazina'),
  'dcaHint': ('Allocate a % of the reserve fund into the BTC war chest.', 'Allouez un % du fonds de réserve au coffre BTC.', 'Asigna un % del fondo de reserva al cofre BTC.', '将储备金的一定比例配置到 BTC 金库。', 'आरक्षित कोष का % BTC युद्ध कोष में आवंटित करें।', 'Maglaan ng % ng reserve fund sa BTC war chest.', 'Przydziel % funduszu rezerwowego do skarbca BTC.', 'Виділіть % резервного фонду в BTC-скарбницю.', 'Tenga % ya mfuko wa akiba kwa hazina ya BTC.'),
  'dcaAllocation': ('Allocation', 'Allocation', 'Asignación', '配置比例', 'आवंटन', 'Alokasyon', 'Alokacja', 'Розподіл', 'Mgawanyo'),
  'dcaFrequency': ('Frequency', 'Fréquence', 'Frecuencia', '频率', 'आवृत्ति', 'Dalas', 'Częstotliwość', 'Частота', 'Mara kwa mara'),
  'dcaProjected': ('Projected per period', 'Projeté par période', 'Proyectado por período', '每期预计', 'प्रति अवधि अनुमानित', 'Inaasahang bawat panahon', 'Prognoza na okres', 'Прогноз на період', 'Inakadiriwa kwa kipindi'),
  'dcaDisclosure': ('Form B disclosure', 'Divulgation formulaire B', 'Divulgación Formulario B', 'B 表披露', 'फॉर्म B प्रकटीकरण', 'Pagsisiwalat sa Form B', 'Ujawnienie formularza B', 'Розкриття форми B', 'Ufichuzi wa Form B'),
  'readinessTitle': ('Rails readiness', 'Préparation des rails', 'Preparación de rails', '通道就绪', 'रेल तैयारी', 'Kahandaan ng rails', 'Gotowość torów', 'Готовність рейлів', 'Utayari wa reli'),
  'readinessHint': ('What it takes to connect each sovereign daemon.', 'Ce qu’il faut pour connecter chaque démon souverain.', 'Qué se necesita para conectar cada demonio soberano.', '连接每个自主守护进程所需的条件。', 'प्रत्येक सॉवरेन डेमॉन को जोड़ने के लिए क्या चाहिए।', 'Ano ang kailangan para ikonekta ang bawat daemon.', 'Co potrzeba, aby podłączyć każdy demon.', 'Що потрібно для підключення кожного демона.', 'Kinachohitajika kuunganisha kila daemon.'),
  'readinessEnv': ('Env', 'Environnement', 'Env', '环境变量', 'एनवी', 'Env', 'Env', 'Env', 'Env'),
  'readinessGuide': ('Deploy guide', 'Guide de déploiement', 'Guía de despliegue', '部署指南', 'डिप्लॉय गाइड', 'Gabay sa pag-deploy', 'Przewodnik wdrożenia', 'Посібник із розгортання', 'Mwongozo wa kupeleka'),
  'readinessConnected': ('connected', 'connecté', 'conectado', '已连接', 'जुड़ा', 'konektado', 'połączono', 'підключено', 'imeunganishwa'),
  'readinessConfigured': ('configured', 'configuré', 'configurado', '已配置', 'कॉन्फ़िगर', 'naka-configure', 'skonfigurowano', 'налаштовано', 'imesanidiwa'),
  'readinessPending': ('pending host', 'hôte en attente', 'host pendiente', '待定主机', 'लंबित होस्ट', 'nakabinbing host', 'oczekujący host', 'очікує хост', 'host inasubiri'),
  'chainViz': ('Chain', 'Chaîne', 'Cadena', '链', 'चेन', 'Chain', 'Łańcuch', 'Ланцюг', 'Mnyororo'),
  'offlineTitle': ('You’re offline', 'Vous êtes hors ligne', 'Estás sin conexión', '您已离线', 'आप ऑफ़लाइन हैं', 'Offline ka', 'Jesteś offline', 'Ви offline', 'Uko nje ya mtandao'),
  'offlineText': ('The cached app is still here — reconnect to sync.', 'L’application en cache reste disponible — reconnectez-vous pour synchroniser.', 'La app en caché sigue aquí — reconéctate para sincronizar.', '缓存的应用程序仍在 — 重新连接以同步。', 'कैश किया ऐप अभी भी यहाँ है — सिंक के लिए पुनः कनेक्ट करें।', 'Nandito pa ang naka-cache na app — kumonekta muli para mag-sync.', 'Aplikacja w pamięci podręcznej jest — połącz się, aby zsynchronizować.', 'Кешований застосунок тут — підключіться для синхронізації.', 'App iliyohifadhiwa iko hapa — unganisha tena kusawazisha.'),
  'installApp': ('Install app', 'Installer l’application', 'Instalar aplicación', '安装应用', 'ऐप इंस्टॉल करें', 'I-install ang app', 'Zainstaluj aplikację', 'Встановити застосунок', 'Sakinisha programu'),
  'connectTitle': ('Connect your host', 'Connectez votre hôte', 'Conecta tu host', '连接您的主机', 'अपना होस्ट कनेक्ट करें', 'Ikonekta ang iyong host', 'Podłącz swój host', 'Підключіть свій хост', 'Unganisha hosti yako'),
  'connectHint': ('Point the site at your OpenStrata backend to flip from demo to live.', 'Pointez le site vers votre backend OpenStrata pour passer de démo à direct.', 'Apunta el sitio a tu backend OpenStrata para pasar de demo a vivo.', '将站点指向您的 OpenStrata 后端，从演示切换为实时。', 'डेमो से लाइव में जाने के लिए साइट को अपने OpenStrata बैकएंड पर इंगित करें।', 'Ituro ang site sa iyong OpenStrata backend para lumipat mula demo patungong live.', 'Wskaż witrynie swój backend OpenStrata, aby przejść z demo na żywo.', 'Спрямуйте сайт на ваш backend OpenStrata, щоб перейти з демо на живе.', 'Elekeza tovuti kwenye backend yako ya OpenStrata kubadili kutoka demo hadi moja kwa moja.'),
  'connectSteps': ('Set PUBLIC_API_BASE_URL at build time, or openstrata-api-base in this browser, then sign in.', 'Définissez PUBLIC_API_BASE_URL au build, ou openstrata-api-base dans ce navigateur, puis connectez-vous.', 'Define PUBLIC_API_BASE_URL al compilar, u openstrata-api-base en este navegador, y luego inicia sesión.', '在构建时设置 PUBLIC_API_BASE_URL，或在此浏览器中设置 openstrata-api-base，然后登录。', 'बिल्ड पर PUBLIC_API_BASE_URL सेट करें, या इस ब्राउज़र में openstrata-api-base, फिर साइन इन करें।', 'Itakda ang PUBLIC_API_BASE_URL sa build, o openstrata-api-base sa browser na ito, pagkatapos mag-sign in.', 'Ustaw PUBLIC_API_BASE_URL przy budowie lub openstrata-api-base w tej przeglądarce, potem zaloguj się.', 'Встановіть PUBLIC_API_BASE_URL при збірці або openstrata-api-base у цьому браузері, потім увійдіть.', 'Weka PUBLIC_API_BASE_URL wakati wa kuunda, au openstrata-api-base kwenye kivinjari hiki, kisha ingia.'),
  'connectDemo': ('Demo mode — curated sample data shown.', 'Mode démo — données d’exemple affichées.', 'Modo demo — se muestran datos de muestra.', '演示模式 — 显示精选示例数据。', 'डेमो मोड — चुनिंदा नमूना डेटा दिखाया गया।', 'Demo mode — ipinapakita ang sample data.', 'Tryb demo — pokazywane przykładowe dane.', 'Демо-режим — показано зразкові дані.', 'Hali ya demo — data ya sampuli inaonyeshwa.'),

  # ---- Batch: enhanced auth flow ----
  'authWelcomeBack': ('Welcome back', 'Bon retour', 'Bienvenido de nuevo', '欢迎回来', 'वापसी पर स्वागत है', 'Maligayang pagbabalik', 'Witaj ponownie', 'З поверненням', 'Karibu tena'),
  'authCreateHeading': ('Start your workspace', 'Lancez votre espace', 'Inicia tu espacio', '开始您的工作区', 'अपना कार्यक्षेत्र शुरू करें', 'Simulan ang iyong workspace', 'Rozpocznij swój obszar', 'Почніть свій простір', 'Anza nafasi yako'),
  'authStepBuilding': ('Your building', 'Votre immeuble', 'Tu edificio', '您的楼宇', 'आपका भवन', 'Iyong gusali', 'Twój budynek', 'Ваш будинок', 'Jengo lako'),
  'authStepAccount': ('Your account', 'Votre compte', 'Tu cuenta', '您的账户', 'आपका खाता', 'Iyong account', 'Twoje konto', 'Ваш акаунт', 'Akaunti yako'),
  'authContinue': ('Continue', 'Continuer', 'Continuar', '继续', 'जारी रखें', 'Magpatuloy', 'Kontynuuj', 'Продовжити', 'Endelea'),
  'authBack': ('Back', 'Retour', 'Atrás', '返回', 'वापस', 'Bumalik', 'Wstecz', 'Назад', 'Rudi'),
  'authEmailInvalid': ('Enter a valid email address', 'Entrez une adresse courriel valide', 'Ingresa un correo válido', '请输入有效的邮箱地址', 'मान्य ईमेल दर्ज करें', 'Maglagay ng wastong email', 'Podaj prawidłowy adres e-mail', 'Введіть дійсну адресу', 'Weka barua pepe halali'),
  'authPasswordHint': ('At least 8 characters', 'Au moins 8 caractères', 'Al menos 8 caracteres', '至少 8 个字符', 'कम से कम 8 अक्षर', 'Hindi bababa sa 8 character', 'Co najmniej 8 znaków', 'Щонайменше 8 символів', 'Angalau herufi 8'),
  'authStrengthWeak': ('Weak', 'Faible', 'Débil', '弱', 'कमज़ोर', 'Mahina', 'Słabe', 'Слабкий', 'Dhaifu'),
  'authStrengthOk': ('Okay', 'Correct', 'Aceptable', '一般', 'ठीक', 'Katamtaman', 'Średnie', 'Нормальний', 'Sawa'),
  'authStrengthStrong': ('Strong', 'Fort', 'Fuerte', '强', 'मज़बूत', 'Malakas', 'Silne', 'Сильний', 'Imara'),
  'authShowPassword': ('Show password', 'Afficher le mot de passe', 'Mostrar contraseña', '显示密码', 'पासवर्ड दिखाएँ', 'Ipakita ang password', 'Pokaż hasło', 'Показати пароль', 'Onyesha nywila'),
  'authHidePassword': ('Hide password', 'Masquer le mot de passe', 'Ocultar contraseña', '隐藏密码', 'पासवर्ड छिपाएँ', 'Itago ang password', 'Ukryj hasło', 'Сховати пароль', 'Ficha nywila'),
  'authDemoBrowse': ('Just exploring? Browse the live demo', 'Vous explorez ? Parcourez la démo', '¿Solo exploras? Navega la demo', '只是看看？浏览演示', 'सिर्फ देख रहे हैं? डेमो देखें', 'Nag-e-explore lang? I-browse ang demo', 'Tylko przeglądasz? Zobacz demo', 'Просто переглядаєте? Перегляньте демо', 'Unachunguza tu? Tazama demo'),
  'authSecureNote': ('No card required · your host, your keys', 'Aucune carte requise · votre hôte, vos clés', 'Sin tarjeta · tu host, tus llaves', '无需银行卡 · 您的主机，您的密钥', 'कोई कार्ड नहीं · आपका होस्ट, आपकी कुंजियाँ', 'Walang card na kinakailangan · iyong host, iyong mga susi', 'Bez karty · twój host, twoje klucze', 'Без карти · ваш хост, ваші ключі', 'Hakuna kadi · hosti yako, funguo zako'),
  'authTrustChain': ('Chain-verified ledger', 'Grand livre vérifié par chaîne', 'Libro mayor verificado en cadena', '链上验证账本', 'चेन-सत्यापित लेजर', 'Chain-verified ledger', 'Rejestr zweryfikowany łańcuchem', 'Ланцюг-перевірений реєстр', 'Leja iliyothibitishwa kwa mnyororo'),
  'authTrustChainText': ('Every balance is tamper-evident against the hash chain.', 'Chaque solde est inviolable contre la chaîne de hachage.', 'Cada saldo es a prueba de manipulación.', '每个余额都通过哈希链防篡改。', 'हर शेष हैश चेन के विरुद्ध छेड़छाड़-प्रमाणित है।', 'Bawat balanse ay tamper-evident laban sa hash chain.', 'Każde saldo jest odporne na manipulacje.', 'Кожен баланс захищений від втручання.', 'Kila salio halina udanganyifu dhidi ya mnyororo wa hashi.'),
  'authTrustRails': ('Sovereign rails', 'Rails souverains', 'Rails soberanos', '自主通道', 'सॉवरेन रेल्स', 'Mga sovereign rail', 'Suwerenne tory', 'Суверенні рейли', 'Reli huru'),
  'authTrustRailsText': ('Fiat, on-chain and Lightning — keys stay with your council.', 'Fiat, on-chain et Lightning — les clés restent au conseil.', 'Fiat, on-chain y Lightning — las llaves quedan en el consejo.', '法币、链上与闪电 — 密钥由理事会持有。', 'फिएट, ऑन-चेन और लाइटनिंग — कुंजियाँ परिषद के पास रहती हैं।', 'Fiat, on-chain at Lightning — nananatili ang mga susi sa iyong konseho.', 'Fiat, on-chain i Lightning — klucze zostają w radzie.', 'Фіат, on-chain і Lightning — ключі залишаються в раді.', 'Fiat, on-chain na Lightning — funguo zinabaki kwa baraza lako.'),
  'authTrustCompliance': ('BC compliance', 'Conformité BC', 'Cumplimiento BC', '卑诗省合规', 'BC अनुपालन', 'Pagsunod sa BC', 'Zgodność BC', 'Відповідність BC', 'Uzingatiaji wa BC'),
  'authTrustComplianceText': ('Rosa answers with citations; statutory deadlines are tracked.', 'Rosa répond avec des citations ; les délais légaux sont suivis.', 'Rosa responde con citas; los plazos se rastrean.', 'Rosa 引用来源作答；法定截止日期有跟踪。', 'रोसा उद्धरण के साथ उत्तर देता है; वैधानिक समय-सीमाएँ ट्रैक होती हैं।', 'Sumasagot si Rosa nang may siping; sinusubaybayan ang mga deadline.', 'Rosa odpowiada z cytatami; terminy są śledzone.', 'Rosa відповідає з цитатами; терміни відстежуються.', 'Rosa hujibu kwa nukuu; muda wa kisheria unafuatiliwa.'),
  'authSigningIn': ('Signing in…', 'Connexion…', 'Iniciando sesión…', '正在登录…', 'साइन इन हो रहा है…', 'Nagse-sign in…', 'Logowanie…', 'Вхід…', 'Inaingia…'),
  'authCreating': ('Creating workspace…', 'Création de l’espace…', 'Creando espacio…', '正在创建工作区…', 'कार्यक्षेत्र बन रहा है…', 'Gumagawa ng workspace…', 'Tworzenie obszaru…', 'Створення простору…', 'Inaunda nafasi…'),
  'welcomeBackTitle': ('Welcome back', 'Bon retour', 'Bienvenido de nuevo', '欢迎回来', 'वापसी पर स्वागत है', 'Maligayang pagbabalik', 'Witaj ponownie', 'З поверненням', 'Karibu tena'),
  'authWelcomeBackText': ('Your workspace is loading — balances, deadlines, and the ledger are on their way.', 'Votre espace se charge — soldes, échéances et grand livre arrivent.', 'Tu espacio se está cargando — saldos, plazos y libro mayor en camino.', '工作区正在加载 — 余额、截止日期和账本即将呈现。', 'आपका कार्यक्षेत्र लोड हो रहा है — शेष, समय-सीमाएँ और लेजर आ रहे हैं।', 'Naglo-load ang iyong workspace — paparating na ang mga balanse, deadline, at ledger.', 'Twój obszar się ładuje — salda, terminy i rejestr w drodze.', 'Ваш простір завантажується — баланси, терміни та реєстр уже в дорозі.', 'Nafasi yako inapakia — salio, muda na leja vinakuja.'),
  'authCreatedText': ('Your council workspace is ready — we’re pulling in your building now.', 'Votre espace de conseil est prêt — nous chargeons votre immeuble.', 'Tu espacio de consejo está listo — cargamos tu edificio.', '您的理事会工作区已就绪 — 正在加载您的楼宇。', 'आपका परिषद कार्यक्षेत्र तैयार है — हम आपका भवन ला रहे हैं।', 'Handa na ang iyong council workspace — kinukuha na namin ang iyong gusali.', 'Twój obszar rady jest gotowy — ładujemy twój budynek.', 'Ваш простір ради готовий — завантажуємо ваш будинок.', 'Nafasi yako ya baraza iko tayari — tunaleta jengo lako.'),
  'authLoadingWorkspace': ('Loading your workspace…', 'Chargement de votre espace…', 'Cargando tu espacio…', '正在加载您的工作区…', 'आपका कार्यक्षेत्र लोड हो रहा है…', 'Naglo-load ng iyong workspace…', 'Ładowanie Twojego obszaru…', 'Завантаження вашого простору…', 'Inapakia nafasi yako…'),
}

# Idempotency: drop keys that already exist in the English block (so re-runs
# after editing KEYS never duplicate earlier insertions).
EN_HEAD = src.index('export const english: Translation = {')
EN_TAIL = src.index('\n};', EN_HEAD)
en_existing = set(re.findall(r"([A-Za-z]+): '", src[EN_HEAD:EN_TAIL]))
KEYS = {k: v for k, v in KEYS.items() if k not in en_existing}

# Build insertion strings.
type_keys = ' '.join(f'{k}: string;' for k in KEYS)
en_keys = ' '.join(f"{k}: '{v[0]}'," for k, v in KEYS.items())

# 1. Type — insert before the closing ";\n}" of the Translation type.
type_idx = src.find('};\n\nexport const english')
assert type_idx > 0
src = src[:type_idx] + ' ' + type_keys + src[type_idx:]

# 2. English — append before the closing of the english object (idempotent
#    across runs: each run appends after the previous run's last key).
en_start = src.index('export const english: Translation = {')
en_body_end = src.index('\n};', en_start)
en_body = src[en_start:en_body_end].rstrip()
if not en_body.endswith(','):
    en_body += ','
src = src[:en_start] + en_body + ' ' + en_keys + '\n};' + src[en_body_end + 3:]

# 3. Locale blocks — insert per-locale translations before each block's final ' }'.
locale_codes = ['fr', 'es', 'zh', 'hi', 'fil', 'pl', 'uk', 'sw']
for idx, code in enumerate(locale_codes):
    block_re = re.compile(rf"^  {code}: \{{ \.\.\.english,(.*?)( \}},?)$", re.M | re.S)
    m = block_re.search(src)
    assert m, f'locale block {code} not found'
    trans = ' '.join(f"{k}: '{v[idx+1]}'," for k, v in KEYS.items())
    closing = m.group(2).strip()  # '}' or '},'
    indent = m.group(0)[:2]  # '  ' leading indent
    content = m.group(1).rstrip()
    if not content.endswith(','):
        content += ','
    new_block = indent + code + ': { ...english,' + content + ' ' + trans + ' ' + closing
    src = src[:m.start()] + new_block + src[m.end():]

open(path, 'w').write(src)
print(f'added {len(KEYS)} keys x 9 locales')
