<script>
  /** Renders the family legal document body (privacy / terms) with its own typography.
   *  The copy is the shared family source, generated by HQ task t_9286cf15 — never edited here. */
  export let html = '';
  export let page = '';
</script>

<article class="legal-doc" data-legal-page={page}>
  {@html html}
</article>

<style>
  .legal-doc {
    max-width: 46rem;
    margin: 0 auto;
    padding: 2.5rem 1.25rem 4rem;
    line-height: 1.65;
  }
  .legal-doc :global(h1) {
    font-size: 1.9rem;
    line-height: 1.2;
    margin: 0 0 0.5rem;
  }
  .legal-doc :global(h2) {
    font-size: 1.25rem;
    margin: 2.25rem 0 0.6rem;
  }
  .legal-doc :global(h3) {
    font-size: 1.05rem;
    margin: 1.75rem 0 0.4rem;
  }
  .legal-doc :global(p),
  .legal-doc :global(li) {
    margin: 0.5rem 0;
  }
  .legal-doc :global(ul) {
    list-style: disc;
    padding-left: 1.35rem;
  }
  .legal-doc :global(ol) {
    list-style: decimal;
    padding-left: 1.35rem;
  }
  .legal-doc :global(table) {
    width: 100%;
    border-collapse: collapse;
    margin: 1rem 0;
    font-size: 0.94rem;
    display: block;
    overflow-x: auto;
  }
  .legal-doc :global(th),
  .legal-doc :global(td) {
    border: 1px solid #e3e6ea;
    padding: 0.5rem 0.6rem;
    text-align: left;
    vertical-align: top;
  }
  .legal-doc :global(th) {
    background: #f7f8fa;
  }
  .legal-doc :global(blockquote) {
    margin: 1rem 0;
    padding: 0.75rem 1rem;
    border-left: 3px solid #b8893a;
    background: #f7f8fa;
    border-radius: 0 6px 6px 0;
  }
  .legal-doc :global(code) {
    background: #f7f8fa;
    padding: 0.1rem 0.35rem;
    border-radius: 4px;
    font-size: 0.9em;
  }
  .legal-doc :global(hr) {
    border: 0;
    border-top: 1px solid #e3e6ea;
    margin: 2.5rem 0;
  }
</style>
